name: 新功能请求 / Feature Request
description: 写下您关于新功能的一些建议 / Write down your suggestions for new features
title: "[Feat]: "
type: feature
body:
    - type: markdown
      attributes:
          value: "# 新功能请求 / Feature Request"
    - type: markdown
      attributes:
          value: "> 如果只是某些想法，而不是具体的新功能，需要在 [Discussions](https://github.com/TouchController/TouchController/discussions/new?category=%E6%83%B3%E6%B3%95) 中提交 / If you just have some ideas, not specific feature requests, please submit them in [Discussions](https://github.com/TouchController/TouchController/discussions/new?category=%E6%83%B3%E6%B3%95)"
    - type: checkboxes
      id: feature_check
      attributes:
          label: "检查项 / Checklist"
          description: "在提交前，请确认以下内容 / Before submitting, please confirm the following"
          options:
              - label: "此功能未被提出过（可以在[这里](https://github.com/TouchController/TouchController/issues?q=is%3Aissue%20type%3AFeature)进行搜索） / This feature has not been proposed before (you can search [here](https://github.com/TouchController/TouchController/issues?q=is%3Aissue%20type%3AFeature))"
                required: true
              - label: "此功能不在 [Pull Requests](https://github.com/TouchController/TouchController/pulls) 中 / This feature is not in [Pull Requests](https://github.com/TouchController/TouchController/pulls)"
                required: true
              - label: "对应项目的最新版本并未添加此功能 / This feature is not added in the latest version of the corresponding project"
                required: true
    - type: dropdown
      id: bug_project
      attributes:
          label: "项目 / Project"
          description: "出现问题的对应项目 / Corresponding project where the issue occurs"
          options:
              - TouchController
              - Combine
              - BlazeRod
              - ArmorStand
              - AuthProxy
              - BlazeSDL
              - PathFlow
              - FastMerger
              - rules_mc
          default: 0
      validations:
          required: true
    - type: input
      id: feature_summary
      attributes:
          label: "简述 / Summary"
          description: "请简要叙述您所希望添加的新功能 / Please briefly describe the new feature you want to add"
          placeholder: |
              <对此功能的简要描述 / Brief description of this feature>
          required: true
    - type: textarea
      id: feature_details
      attributes:
          label: "详细内容 / Details"
          description: "请详细描述需要此功能的原因，以及此功能的内容 / Please describe in detail why this feature is needed and what it should do"
          placeholder: |
              <需要此功能的原因，以及此功能的详细内容 / Reasons why this feature is needed, and detailed content of this feature>
          required: true
    - type: markdown
      attributes:
          value: "### 感谢您对 TouchController 的支持！ / Thank you for your support of TouchController!"
