license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="touchcontroller_api"
version="${version}"
displayName="${name}"
displayURL="${home_page}"
logoFile="icon.png"
authors="fifth_light"
description='''${description}'''
